#!/usr/bin/env node
/**
 * add-plants.js — generate a Flyway migration, write i18n files, and update tests for new plants.
 *
 * Usage:
 *   node scripts/add-plants.js path/to/spec.json [--images] [--dry-run]
 *
 * The script will:
 *   1. Auto-detect the next migration version number.
 *   2. Write the SQL migration to src/main/resources/db/migration/V<N>__<description>.sql
 *   3. Write translations directly into frontend/src/i18n/en.js, nl.js, and es.js.
 *   4. Update plant and migration counts in MigrationTest.kt.
 *   5. With --images: download plant images from Wikipedia Commons (legal, freely licensed).
 *   6. With --dry-run: print all planned changes without writing to disk.
 *
 * See scripts/plant-spec.example.json for the full spec format.
 * Set "wikipediaPage" on a plant to control which Wikipedia article is used for the image.
 */

const fs    = require('fs')
const path  = require('path')
const https = require('https')
const http  = require('http')

// ── Paths ─────────────────────────────────────────────────────────────────────

const ROOT           = path.resolve(__dirname, '..')
const MIGRATIONS     = path.join(ROOT, 'src/main/resources/db/migration')
const IMAGES_DIR     = path.join(ROOT, 'src/main/resources/static/images/plants')
const I18N_DIR       = path.join(ROOT, 'frontend/src/i18n')
const MIGRATION_TEST = path.join(ROOT, 'src/test/kotlin/org/marnixrenne/kitchengarden/MigrationTest.kt')

// ── Helpers ───────────────────────────────────────────────────────────────────

function q(str) {
  return str.replace(/'/g, "''")
}

function nextVersion() {
  const nums = fs.readdirSync(MIGRATIONS)
    .map(f => f.match(/^V(\d+)__/))
    .filter(Boolean)
    .map(m => parseInt(m[1], 10))
  return Math.max(...nums) + 1
}

// ── SQL generation ────────────────────────────────────────────────────────────

function generateSQL(spec, imageUpdates = []) {
  const lines = []
  const { plants, migrationDescription } = spec
  const desc = (migrationDescription || 'add_plants').replace(/\s+/g, '_')

  lines.push(`-- Auto-generated by scripts/add-plants.js`)
  lines.push(`-- Description: ${desc}`)
  lines.push(``)

  // INSERT PLANTS
  lines.push(`-- ============================================================`)
  lines.push(`-- INSERT PLANTS`)
  lines.push(`-- ============================================================`)
  lines.push(``)
  lines.push(`INSERT INTO pts_plants (id, name, category, emoji) VALUES`)
  lines.push(plants.map(p => `    (gen_random_uuid(), '${q(p.name)}', '${q(p.category)}', '${p.emoji}')`).join(',\n') + ';')
  lines.push(``)

  // LATIN NAMES
  const withLatin = plants.filter(p => p.latinName)
  if (withLatin.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- LATIN NAMES`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withLatin) {
      lines.push(`UPDATE pts_plants SET latin_name = '${q(p.latinName)}' WHERE name = '${q(p.name)}';`)
    }
    lines.push(``)
  }

  // SOWING INFO
  const withSowing = plants.filter(p => p.sowing)
  if (withSowing.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- SOWING INFO`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withSowing) {
      const s   = p.sowing
      const sets = []
      if (s.method             != null) sets.push(`sowing_method = '${q(s.method)}'`)
      if (s.seedDepthMm        != null) sets.push(`seed_depth_mm = ${s.seedDepthMm}`)
      if (s.spacingCm          != null) sets.push(`spacing_cm = ${s.spacingCm}`)
      if (s.germinationMinDays != null) sets.push(`germination_days_min = ${s.germinationMinDays}`)
      if (s.germinationMaxDays != null) sets.push(`germination_days_max = ${s.germinationMaxDays}`)
      if (s.daysToMaturityMin  != null) sets.push(`days_to_maturity_min = ${s.daysToMaturityMin}`)
      if (s.daysToMaturityMax  != null) sets.push(`days_to_maturity_max = ${s.daysToMaturityMax}`)
      if (s.frostTolerance     != null) sets.push(`frost_tolerance = '${q(s.frostTolerance)}'`)
      if (sets.length) lines.push(`UPDATE pts_plants SET ${sets.join(', ')} WHERE name = '${q(p.name)}';`)
    }
    lines.push(``)
  }

  // HEIGHT
  const withHeight = plants.filter(p => p.heightCm)
  if (withHeight.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- HEIGHT`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withHeight) {
      const { min, max } = p.heightCm
      lines.push(`UPDATE pts_plants SET height_min_cm = ${min}, height_max_cm = ${max} WHERE name = '${q(p.name)}';`)
    }
    lines.push(``)
  }

  // IMAGE URLS
  if (imageUpdates.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- IMAGE URLS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const { name, path: imgPath } of imageUpdates) {
      lines.push(`UPDATE pts_plants SET image_url = '${q(imgPath)}' WHERE name = '${q(name)}';`)
    }
    lines.push(``)
  }

  // PRUNING
  const withPruning = plants.filter(p => p.pruning)
  if (withPruning.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- PRUNING`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withPruning) {
      const sets = []
      if (p.pruning.type) sets.push(`pruning_type = '${q(p.pruning.type)}'`)
      if (p.pruning.tip)  sets.push(`pruning_tip  = '${q(p.pruning.tip)}'`)
      if (sets.length) lines.push(`UPDATE pts_plants SET ${sets.join(', ')} WHERE name = '${q(p.name)}';`)
    }
    lines.push(``)
  }

  // FERTILIZER
  const withFertilizer = plants.filter(p => p.fertilizer)
  if (withFertilizer.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- FERTILIZER`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withFertilizer) {
      const sets = []
      if (p.fertilizer.type) sets.push(`fertilizer_type = '${q(p.fertilizer.type)}'`)
      if (p.fertilizer.tip)  sets.push(`fertilizer_tip  = '${q(p.fertilizer.tip)}'`)
      if (sets.length) lines.push(`UPDATE pts_plants SET ${sets.join(', ')} WHERE name = '${q(p.name)}';`)
    }
    lines.push(``)
  }

  // SEEDING MONTHS
  const withSeeding = plants.filter(p => p.seedingMonths?.length)
  if (withSeeding.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- SEEDING MONTHS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    lines.push(`INSERT INTO pts_seeding_months (plant_id, month_num)`)
    lines.push(`SELECT p.id, m.month_num`)
    lines.push(`FROM pts_plants p`)
    lines.push(`JOIN (VALUES`)
    lines.push(withSeeding.flatMap(p => p.seedingMonths.map(m => `    ('${q(p.name)}', ${m})`)).join(',\n'))
    lines.push(`) AS m(plant_name, month_num) ON p.name = m.plant_name;`)
    lines.push(``)
  }

  // HARVESTING MONTHS
  const withHarvest = plants.filter(p => p.harvestingMonths?.length)
  if (withHarvest.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- HARVESTING MONTHS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    lines.push(`INSERT INTO pts_harvesting_months (plant_id, month_num)`)
    lines.push(`SELECT p.id, m.month_num`)
    lines.push(`FROM pts_plants p`)
    lines.push(`JOIN (VALUES`)
    lines.push(withHarvest.flatMap(p => p.harvestingMonths.map(m => `    ('${q(p.name)}', ${m})`)).join(',\n'))
    lines.push(`) AS m(plant_name, month_num) ON p.name = m.plant_name;`)
    lines.push(``)
  }

  // COUNTRIES
  const withCountries = plants.filter(p => p.countries?.length)
  if (withCountries.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- COUNTRY ASSOCIATIONS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    lines.push(`INSERT INTO pts_plant_countries (plant_id, country_code)`)
    lines.push(`SELECT p.id, m.country_code`)
    lines.push(`FROM pts_plants p`)
    lines.push(`JOIN (VALUES`)
    lines.push(withCountries.flatMap(p => p.countries.map(c => `    ('${q(p.name)}', '${c}')`)).join(',\n'))
    lines.push(`) AS m(plant_name, country_code) ON p.name = m.plant_name;`)
    lines.push(``)
  }

  // COMPANION PLANTS
  const withCompanions = plants.filter(p => p.companions?.good?.length || p.companions?.bad?.length)
  if (withCompanions.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- COMPANION PLANTS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withCompanions) {
      for (const c of (p.companions?.good ?? [])) {
        lines.push(`INSERT INTO pts_companion_plants (plant_id, companion_id, relationship)`)
        lines.push(`SELECT v1.id, v2.id, 'good' FROM pts_plants v1, pts_plants v2 WHERE v1.name = '${q(p.name)}' AND v2.name = '${q(c)}'`)
        lines.push(`ON CONFLICT (plant_id, companion_id) DO NOTHING;`)
      }
      for (const c of (p.companions?.bad ?? [])) {
        lines.push(`INSERT INTO pts_companion_plants (plant_id, companion_id, relationship)`)
        lines.push(`SELECT v1.id, v2.id, 'bad' FROM pts_plants v1, pts_plants v2 WHERE v1.name = '${q(p.name)}' AND v2.name = '${q(c)}'`)
        lines.push(`ON CONFLICT (plant_id, companion_id) DO NOTHING;`)
      }
      lines.push(``)
    }
  }

  // INSECTS
  const withInsects = plants.filter(p =>
    p.insects?.pollinators?.length || p.insects?.beneficial?.length || p.insects?.pests?.length
  )
  if (withInsects.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- INSECTS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withInsects) {
      for (const i of (p.insects?.pollinators ?? [])) {
        lines.push(`INSERT INTO pts_plant_insects (plant_id, insect_name, insect_type) SELECT id, '${i}', 'pollinator' FROM pts_plants WHERE name = '${q(p.name)}';`)
      }
      for (const i of (p.insects?.beneficial ?? [])) {
        lines.push(`INSERT INTO pts_plant_insects (plant_id, insect_name, insect_type) SELECT id, '${i}', 'beneficial' FROM pts_plants WHERE name = '${q(p.name)}';`)
      }
      for (const i of (p.insects?.pests ?? [])) {
        lines.push(`INSERT INTO pts_plant_insects (plant_id, insect_name, insect_type) SELECT id, '${i}', 'pest' FROM pts_plants WHERE name = '${q(p.name)}';`)
      }
      lines.push(``)
    }
  }

  return { sql: lines.join('\n'), desc }
}

// ── i18n file writers ─────────────────────────────────────────────────────────

function jsKey(name) {
  // Names with non-word chars (spaces, apostrophes, etc.) need quotes
  return /[^a-zA-Z0-9_$]/.test(name) ? `'${name.replace(/'/g, "\\'")}'` : name
}

function jsEntry(name, value, indent) {
  const key     = jsKey(name)
  const padded  = key.padEnd(22)
  const escaped = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  return `${indent}${padded}: '${escaped}',`
}

/**
 * Locate the line range (exclusive) to insert new entries into a named section.
 *
 * sectionSelector examples:
 *   'plants'           →  finds `  plants: {` then its closing `  },`
 *   'descriptions'     →  finds `  descriptions: {` then its closing `  },`
 *   'pruning.tips'     →  finds `  pruning: {`, then `    tips: {`, then `    },`
 *   'fertilizer.tips'  →  finds `  fertilizer: {`, then `    tips: {`, then `    },`
 *
 * Returns [sectionBodyStart, insertBeforeLineIdx] or null if not found.
 */
function findInsertPoint(lines, sectionSelector) {
  const parts = sectionSelector.split('.')

  if (parts.length === 2) {
    const [parent, child] = parts
    // Find parent header (indent 2)
    let parentIdx = -1
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].trimEnd() === `  ${parent}: {`) { parentIdx = i; break }
    }
    if (parentIdx < 0) return null

    // Find child header (indent 4) inside parent
    for (let i = parentIdx + 1; i < lines.length; i++) {
      if (lines[i].trimEnd() === `    ${child}: {`) {
        // Find closing (indent 4)
        for (let j = i + 1; j < lines.length; j++) {
          if (lines[j].trimEnd() === '    },') return [i + 1, j]
        }
      }
      if (lines[i].trimEnd() === '  },') break // left parent scope
    }
  } else {
    // Top-level section (indent 2)
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].trimEnd() === `  ${parts[0]}: {`) {
        for (let j = i + 1; j < lines.length; j++) {
          if (lines[j].trimEnd() === '  },') return [i + 1, j]
        }
      }
    }
  }
  return null
}

function writeI18nSection(filePath, sectionSelector, entries, dryRun) {
  if (!entries.length) return

  const content = fs.readFileSync(filePath, 'utf8')
  const lines   = content.split('\n')
  const range   = findInsertPoint(lines, sectionSelector)

  if (!range) {
    console.warn(`  ⚠️  Section "${sectionSelector}" not found in ${path.basename(filePath)} — skipping`)
    return
  }

  const [bodyStart, insertBefore] = range
  const existingBlock = lines.slice(bodyStart, insertBefore).join('\n')

  // Skip plants already present (key may be followed by spaces before the colon)
  const toInsert = entries.filter(({ name }) => {
    const k       = jsKey(name)
    const escaped = k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    return !new RegExp(escaped + '\\s*:').test(existingBlock)
  })
  if (!toInsert.length) return

  const indent   = sectionSelector.includes('.') ? '      ' : '    '
  const newLines = toInsert.map(e => jsEntry(e.name, e.value, indent))

  if (dryRun) {
    console.log(`  [dry-run] ${path.basename(filePath)} › ${sectionSelector}: +${toInsert.length}`)
    newLines.forEach(l => console.log(`    ${l}`))
    return
  }

  lines.splice(insertBefore, 0, ...newLines)
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8')
  console.log(`  ✅ ${path.basename(filePath)} › ${sectionSelector}: +${toInsert.length} entries`)
}

function writeI18nUpdates(spec, dryRun) {
  const locales = ['en', 'nl', 'es']

  for (const locale of locales) {
    const filePath = path.join(I18N_DIR, `${locale}.js`)
    if (!fs.existsSync(filePath)) {
      console.warn(`  ⚠️  ${locale}.js not found — skipping`)
      continue
    }

    console.log(`\n── ${locale}.js ────────────────────────────────────────────────`)

    writeI18nSection(filePath, 'plants', spec.plants.map(p => ({
      name:  p.name,
      value: p.i18n?.[locale]?.name ?? p.name,
    })), dryRun)

    writeI18nSection(filePath, 'descriptions',
      spec.plants
        .filter(p => p.i18n?.[locale]?.description)
        .map(p => ({ name: p.name, value: p.i18n[locale].description })),
      dryRun)

    writeI18nSection(filePath, 'pruning.tips',
      spec.plants
        .filter(p => p.pruning && (p.i18n?.[locale]?.pruningTip ?? p.pruning.tip))
        .map(p => ({ name: p.name, value: p.i18n?.[locale]?.pruningTip ?? p.pruning.tip })),
      dryRun)

    writeI18nSection(filePath, 'fertilizer.tips',
      spec.plants
        .filter(p => p.fertilizer && (p.i18n?.[locale]?.fertilizerTip ?? p.fertilizer.tip))
        .map(p => ({ name: p.name, value: p.i18n?.[locale]?.fertilizerTip ?? p.fertilizer.tip })),
      dryRun)
  }
}

// ── MigrationTest.kt update ───────────────────────────────────────────────────

function updateMigrationTest(newPlantCount, newVersion, dryRun) {
  const content = fs.readFileSync(MIGRATION_TEST, 'utf8')

  const migMatch   = content.match(/assertEquals\((\d+), count, "Expected \d+ successful migrations"\)/)
  const plantMatch = content.match(/assertEquals\((\d+), count, "Expected \d+ plants total"\)/)

  if (!migMatch || !plantMatch) {
    console.warn('\n  ⚠️  Could not locate assertEquals lines in MigrationTest.kt — update manually')
    return
  }

  const oldMig   = parseInt(migMatch[1],   10)
  const oldPlant = parseInt(plantMatch[1], 10)
  const newMig   = oldMig   + 1
  const newPlant = oldPlant + newPlantCount

  let updated = content
    // Migration count + "through VN" comment
    .replace(
      /\/\/ V1 through V\d+ \(no V32\)/,
      `// V1 through V${newVersion} (no V32)`
    )
    .replace(
      /assertEquals\(\d+, count, "Expected \d+ successful migrations"\)/,
      `assertEquals(${newMig}, count, "Expected ${newMig} successful migrations")`
    )
    // Plant count + running-total comment — replace "= N" with "+ N (VX) = total"
    .replace(
      /(\/\/ .+) = \d+(\n\s+assertEquals\(\d+, count, "Expected \d+ plants total"\))/,
      (_, commentBase, assertSuffix) =>
        `${commentBase} + ${newPlantCount} (V${newVersion}) = ${newPlant}${assertSuffix}`
    )
    .replace(
      /assertEquals\(\d+, count, "Expected \d+ plants total"\)/,
      `assertEquals(${newPlant}, count, "Expected ${newPlant} plants total")`
    )

  console.log(`\n── MigrationTest.kt ────────────────────────────────────────────`)

  if (dryRun) {
    const origLines = content.split('\n')
    const newLines  = updated.split('\n')
    for (let i = 0; i < Math.max(origLines.length, newLines.length); i++) {
      if (origLines[i] !== newLines[i]) {
        if (origLines[i] !== undefined) console.log(`  - ${origLines[i].trim()}`)
        if (newLines[i]  !== undefined) console.log(`  + ${newLines[i].trim()}`)
      }
    }
    return
  }

  fs.writeFileSync(MIGRATION_TEST, updated, 'utf8')
  console.log(`  ✅ migrations: ${oldMig} → ${newMig}`)
  console.log(`  ✅ plants:     ${oldPlant} → ${newPlant}`)
}

// ── New category check ────────────────────────────────────────────────────────

const KNOWN_CATEGORIES = ['Fruiting', 'Leafy', 'Brassica', 'Root', 'Legume', 'Herb', 'Flower', 'Sea', 'Fruit']

function checkNewCategories(spec) {
  const novel = [...new Set(spec.plants.map(p => p.category))].filter(c => !KNOWN_CATEGORIES.includes(c))
  if (novel.length) {
    console.log(`\n⚠️  New categories detected: ${novel.join(', ')}`)
    console.log(`   Remember to add them to:`)
    console.log(`   1. CATEGORY_ORDER in frontend/src/views/HomeView.vue`)
    console.log(`   2. The 'categories' section in en.js, nl.js, and es.js`)
  }
}

// ── Image download ────────────────────────────────────────────────────────────

function httpsGet(url) {
  return new Promise((resolve, reject) => {
    const mod = url.startsWith('https') ? https : http
    mod.get(url, { headers: { 'User-Agent': 'KitchenGardenBot/1.0' } }, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return resolve(httpsGet(res.headers.location))
      }
      const chunks = []
      res.on('data', c => chunks.push(c))
      res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body: Buffer.concat(chunks) }))
      res.on('error', reject)
    }).on('error', reject)
  })
}

async function fetchWikipediaImageUrl(page) {
  const encoded = encodeURIComponent(page.replace(/ /g, '_'))
  const res = await httpsGet(`https://en.wikipedia.org/api/rest_v1/page/summary/${encoded}`)
  if (res.status !== 200) return null
  const data = JSON.parse(res.body.toString())
  const img  = data.originalimage || data.thumbnail
  return img ? img.source : null
}

async function downloadImages(spec) {
  console.log('\n── Downloading images ────────────────────────────────────────────')
  if (!fs.existsSync(IMAGES_DIR)) fs.mkdirSync(IMAGES_DIR, { recursive: true })

  const imageUpdates = []
  for (const p of spec.plants) {
    const slug = p.name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '')
    const page = p.wikipediaPage || p.name

    process.stdout.write(`  ${p.name}… `)

    let url
    try { url = await fetchWikipediaImageUrl(page) } catch { url = null }

    if (!url) { console.log('no image found on Wikipedia — skipping'); continue }

    const rawExt = url.split('.').pop().split('?')[0].toLowerCase()
    const ext    = rawExt === 'png' ? 'png' : 'jpg'
    const fname  = `${slug}.${ext}`
    const dest   = path.join(IMAGES_DIR, fname)

    try {
      const imgRes = await httpsGet(url)
      if (imgRes.status !== 200) { console.log(`HTTP ${imgRes.status} — skipping`); continue }
      fs.writeFileSync(dest, imgRes.body)
      console.log(`${fname} (${Math.round(imgRes.body.length / 1024)} KB)`)
      imageUpdates.push({ name: p.name, path: `/images/plants/${fname}` })
    } catch (e) {
      console.log(`error: ${e.message}`)
    }
  }
  return imageUpdates
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const args      = process.argv.slice(2)
  const specFile  = args.find(a => !a.startsWith('--'))
  const withImages = args.includes('--images')
  const dryRun    = args.includes('--dry-run')

  if (!specFile) {
    console.error('Usage: node scripts/add-plants.js path/to/spec.json [--images] [--dry-run]')
    console.error('       See scripts/plant-spec.example.json for the spec format.')
    process.exit(1)
  }

  const specPath = path.resolve(process.cwd(), specFile)
  if (!fs.existsSync(specPath)) {
    console.error(`Error: spec file not found: ${specPath}`)
    process.exit(1)
  }

  const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'))
  if (!spec.plants?.length) { console.error('Error: spec.plants is empty.'); process.exit(1) }

  if (dryRun) console.log('\n⚠️  DRY RUN — no files will be modified\n')

  // Download images first so image_url UPDATEs are included in the same migration
  let imageUpdates = []
  if (withImages) imageUpdates = await downloadImages(spec)

  // Write SQL migration
  const version       = nextVersion()
  const { sql, desc } = generateSQL(spec, imageUpdates)
  const migName       = `V${version}__${desc}.sql`
  const migPath       = path.join(MIGRATIONS, migName)

  console.log(`\n── SQL migration ────────────────────────────────────────────────`)
  if (dryRun) {
    console.log(`  [dry-run] Would write: src/main/resources/db/migration/${migName}`)
  } else {
    fs.writeFileSync(migPath, sql, 'utf8')
    console.log(`  ✅ Written: src/main/resources/db/migration/${migName}`)
  }

  // Write i18n files
  writeI18nUpdates(spec, dryRun)

  // Update MigrationTest.kt
  updateMigrationTest(spec.plants.length, version, dryRun)

  // Warn about new categories
  checkNewCategories(spec)

  console.log(`\n── Done ─────────────────────────────────────────────────────────`)
  if (dryRun) {
    console.log(`  Re-run without --dry-run to apply all changes.`)
  } else {
    console.log(`  Start the backend — Flyway will apply V${version} automatically.`)
  }
}

main().catch(e => { console.error(e); process.exit(1) })
