#!/usr/bin/env node
/**
 * add-plants.js — generate a Flyway migration and i18n snippets for new plants.
 *
 * Usage:
 *   node scripts/add-plants.js path/to/spec.json [--images]
 *
 * The script will:
 *   1. Auto-detect the next migration version number.
 *   2. Write the SQL migration to src/main/resources/db/migration/V<N>__<description>.sql
 *   3. Print ready-to-paste i18n snippets for en.js and nl.js.
 *   4. With --images: download plant images from Wikipedia Commons automatically.
 *
 * See scripts/plant-spec.example.json for the full spec format.
 * In the spec, set "wikipediaPage" on a plant to control which Wikipedia article
 * is used for the image (defaults to the plant name).
 */

const fs      = require('fs')
const path    = require('path')
const https   = require('https')
const http    = require('http')

// ── Paths ─────────────────────────────────────────────────────────────────────

const ROOT       = path.resolve(__dirname, '..')
const MIGRATIONS = path.join(ROOT, 'src/main/resources/db/migration')
const IMAGES_DIR = path.join(ROOT, 'src/main/resources/static/images/plants')
const EN_JS      = path.join(ROOT, 'frontend/src/i18n/en.js')
const NL_JS      = path.join(ROOT, 'frontend/src/i18n/nl.js')

// ── Helpers ───────────────────────────────────────────────────────────────────

function nextVersion() {
  const files = fs.readdirSync(MIGRATIONS)
  const nums  = files
    .map(f => f.match(/^V(\d+)__/))
    .filter(Boolean)
    .map(m => parseInt(m[1], 10))
  return Math.max(...nums) + 1
}

function q(str) {
  // Escape single quotes for SQL string literals
  return str.replace(/'/g, "''")
}

function monthList(months) {
  return months.map(m => String(m)).join(', ')
}

// ── SQL generation ────────────────────────────────────────────────────────────

function generateSQL(spec, imageUpdates = []) {
  const lines = []
  const { plants, migrationDescription } = spec

  const desc = (migrationDescription || 'add_plants').replace(/\s+/g, '_')
  lines.push(`-- Auto-generated by scripts/add-plants.js`)
  lines.push(`-- Description: ${desc}`)
  lines.push(``)

  // ── INSERT PLANTS ──────────────────────────────────────────────────────────
  lines.push(`-- ============================================================`)
  lines.push(`-- INSERT PLANTS`)
  lines.push(`-- ============================================================`)
  lines.push(``)
  lines.push(`INSERT INTO pts_plants (id, name, category, emoji) VALUES`)
  const plantRows = plants.map(p =>
    `    (gen_random_uuid(), '${q(p.name)}', '${q(p.category)}', '${p.emoji}')`
  )
  lines.push(plantRows.join(',\n') + ';')
  lines.push(``)

  // ── LATIN NAMES ────────────────────────────────────────────────────────────
  const withLatin = plants.filter(p => p.latinName)
  if (withLatin.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- LATIN NAMES`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withLatin) {
      lines.push(`UPDATE pts_plants SET latin_name = '${q(p.latinName)}' WHERE name = '${q(p.name)}';`)
    }
    lines.push(``)
  }

  // ── SOWING INFO ────────────────────────────────────────────────────────────
  const withSowing = plants.filter(p => p.sowing)
  if (withSowing.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- SOWING INFO`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withSowing) {
      const s = p.sowing
      const sets = []
      if (s.method           != null) sets.push(`sowing_method = '${q(s.method)}'`)
      if (s.seedDepthMm      != null) sets.push(`seed_depth_mm = ${s.seedDepthMm}`)
      if (s.spacingCm        != null) sets.push(`spacing_cm = ${s.spacingCm}`)
      if (s.germinationMinDays != null) sets.push(`germination_days_min = ${s.germinationMinDays}`)
      if (s.germinationMaxDays != null) sets.push(`germination_days_max = ${s.germinationMaxDays}`)
      if (s.daysToMaturityMin  != null) sets.push(`days_to_maturity_min = ${s.daysToMaturityMin}`)
      if (s.daysToMaturityMax  != null) sets.push(`days_to_maturity_max = ${s.daysToMaturityMax}`)
      if (s.frostTolerance   != null) sets.push(`frost_tolerance = '${q(s.frostTolerance)}'`)
      if (sets.length) {
        lines.push(`UPDATE pts_plants SET ${sets.join(', ')} WHERE name = '${q(p.name)}';`)
      }
    }
    lines.push(``)
  }

  // ── HEIGHT ─────────────────────────────────────────────────────────────────
  const withHeight = plants.filter(p => p.heightCm)
  if (withHeight.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- HEIGHT`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withHeight) {
      const { min, max } = p.heightCm
      lines.push(`UPDATE pts_plants SET height_min_cm = ${min}, height_max_cm = ${max} WHERE name = '${q(p.name)}';`)
    }
    lines.push(``)
  }

  // ── IMAGE URLS ─────────────────────────────────────────────────────────────
  if (imageUpdates.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- IMAGE URLS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const { name, path: imgPath } of imageUpdates) {
      lines.push(`UPDATE pts_plants SET image_url = '${q(imgPath)}' WHERE name = '${q(name)}';`)
    }
    lines.push(``)
  }

  // ── PRUNING ────────────────────────────────────────────────────────────────
  const withPruning = plants.filter(p => p.pruning)
  if (withPruning.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- PRUNING`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withPruning) {
      const sets = []
      if (p.pruning.type) sets.push(`pruning_type = '${q(p.pruning.type)}'`)
      if (p.pruning.tip)  sets.push(`pruning_tip  = '${q(p.pruning.tip)}'`)
      if (sets.length) {
        lines.push(`UPDATE pts_plants SET ${sets.join(', ')} WHERE name = '${q(p.name)}';`)
      }
    }
    lines.push(``)
  }

  // ── SEEDING MONTHS ─────────────────────────────────────────────────────────
  const withSeeding = plants.filter(p => p.seedingMonths?.length)
  if (withSeeding.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- SEEDING MONTHS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    lines.push(`INSERT INTO pts_seeding_months (plant_id, month_num)`)
    lines.push(`SELECT p.id, m.month_num`)
    lines.push(`FROM pts_plants p`)
    lines.push(`JOIN (VALUES`)
    const seedRows = withSeeding.flatMap(p =>
      p.seedingMonths.map(m => `    ('${q(p.name)}', ${m})`)
    )
    lines.push(seedRows.join(',\n'))
    lines.push(`) AS m(plant_name, month_num) ON p.name = m.plant_name;`)
    lines.push(``)
  }

  // ── HARVESTING MONTHS ──────────────────────────────────────────────────────
  const withHarvest = plants.filter(p => p.harvestingMonths?.length)
  if (withHarvest.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- HARVESTING MONTHS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    lines.push(`INSERT INTO pts_harvesting_months (plant_id, month_num)`)
    lines.push(`SELECT p.id, m.month_num`)
    lines.push(`FROM pts_plants p`)
    lines.push(`JOIN (VALUES`)
    const harvestRows = withHarvest.flatMap(p =>
      p.harvestingMonths.map(m => `    ('${q(p.name)}', ${m})`)
    )
    lines.push(harvestRows.join(',\n'))
    lines.push(`) AS m(plant_name, month_num) ON p.name = m.plant_name;`)
    lines.push(``)
  }

  // ── COUNTRIES ──────────────────────────────────────────────────────────────
  const withCountries = plants.filter(p => p.countries?.length)
  if (withCountries.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- COUNTRY ASSOCIATIONS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    lines.push(`INSERT INTO pts_plant_countries (plant_id, country_code)`)
    lines.push(`SELECT p.id, m.country_code`)
    lines.push(`FROM pts_plants p`)
    lines.push(`JOIN (VALUES`)
    const countryRows = withCountries.flatMap(p =>
      p.countries.map(c => `    ('${q(p.name)}', '${c}')`)
    )
    lines.push(countryRows.join(',\n'))
    lines.push(`) AS m(plant_name, country_code) ON p.name = m.plant_name;`)
    lines.push(``)
  }

  // ── COMPANION PLANTS ───────────────────────────────────────────────────────
  const withCompanions = plants.filter(p =>
    p.companions?.good?.length || p.companions?.bad?.length
  )
  if (withCompanions.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- COMPANION PLANTS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withCompanions) {
      const good = p.companions?.good ?? []
      const bad  = p.companions?.bad  ?? []
      if (good.length || bad.length) lines.push(`-- ${p.name}`)
      for (const c of good) {
        lines.push(`INSERT INTO pts_companion_plants (plant_id, companion_id, relationship)`)
        lines.push(`SELECT v1.id, v2.id, 'good' FROM pts_plants v1, pts_plants v2 WHERE v1.name = '${q(p.name)}' AND v2.name = '${q(c)}'`)
        lines.push(`ON CONFLICT (plant_id, companion_id) DO NOTHING;`)
      }
      for (const c of bad) {
        lines.push(`INSERT INTO pts_companion_plants (plant_id, companion_id, relationship)`)
        lines.push(`SELECT v1.id, v2.id, 'bad' FROM pts_plants v1, pts_plants v2 WHERE v1.name = '${q(p.name)}' AND v2.name = '${q(c)}'`)
        lines.push(`ON CONFLICT (plant_id, companion_id) DO NOTHING;`)
      }
      lines.push(``)
    }
  }

  // ── INSECTS ────────────────────────────────────────────────────────────────
  const withInsects = plants.filter(p =>
    p.insects?.pollinators?.length || p.insects?.beneficial?.length || p.insects?.pests?.length
  )
  if (withInsects.length) {
    lines.push(`-- ============================================================`)
    lines.push(`-- INSECTS`)
    lines.push(`-- ============================================================`)
    lines.push(``)
    for (const p of withInsects) {
      lines.push(`-- ${p.name}`)
      for (const i of (p.insects?.pollinators ?? [])) {
        lines.push(`INSERT INTO pts_plant_insects (plant_id, insect_name, insect_type) SELECT id, '${i}', 'pollinator' FROM pts_plants WHERE name = '${q(p.name)}';`)
      }
      for (const i of (p.insects?.beneficial ?? [])) {
        lines.push(`INSERT INTO pts_plant_insects (plant_id, insect_name, insect_type) SELECT id, '${i}', 'beneficial' FROM pts_plants WHERE name = '${q(p.name)}';`)
      }
      for (const i of (p.insects?.pests ?? [])) {
        lines.push(`INSERT INTO pts_plant_insects (plant_id, insect_name, insect_type) SELECT id, '${i}', 'pest' FROM pts_plants WHERE name = '${q(p.name)}';`)
      }
      lines.push(``)
    }
  }

  return { sql: lines.join('\n'), desc }
}

// ── i18n snippet generation ───────────────────────────────────────────────────

function generateI18n(spec, locale) {
  const { plants } = spec
  const lines = []

  lines.push(`    // -- paste into the 'plants' section of ${locale}.js --`)
  for (const p of plants) {
    const name = p.i18n?.[locale]?.name ?? p.name
    lines.push(`    '${p.name}': '${name}',`)
  }
  lines.push(``)
  lines.push(`    // -- paste into the 'descriptions' section of ${locale}.js --`)
  for (const p of plants) {
    const desc = p.i18n?.[locale]?.description
    if (desc) {
      lines.push(`    '${p.name}': '${desc.replace(/'/g, "\\'")}',`)
    } else {
      lines.push(`    // '${p.name}': 'TODO',`)
    }
  }

  if (plants.some(p => p.pruning?.tip && p.i18n?.[locale]?.pruningTip)) {
    lines.push(``)
    lines.push(`    // -- paste into pruning.tips section of ${locale}.js --`)
    for (const p of plants) {
      const tip = p.i18n?.[locale]?.pruningTip ?? p.pruning?.tip
      if (tip) {
        lines.push(`    '${p.name}': '${tip.replace(/'/g, "\\'")}',`)
      }
    }
  }

  return lines.join('\n')
}

// ── Image download ────────────────────────────────────────────────────────────

function httpsGet(url) {
  return new Promise((resolve, reject) => {
    const mod = url.startsWith('https') ? https : http
    mod.get(url, { headers: { 'User-Agent': 'KitchenGardenBot/1.0' } }, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return resolve(httpsGet(res.headers.location))
      }
      const chunks = []
      res.on('data', c => chunks.push(c))
      res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body: Buffer.concat(chunks) }))
      res.on('error', reject)
    }).on('error', reject)
  })
}

async function fetchWikipediaImageUrl(page) {
  const encoded = encodeURIComponent(page.replace(/ /g, '_'))
  const res = await httpsGet(`https://en.wikipedia.org/api/rest_v1/page/summary/${encoded}`)
  if (res.status !== 200) return null
  const data = JSON.parse(res.body.toString())
  const img  = data.originalimage || data.thumbnail
  return img ? img.source : null
}

async function downloadImages(spec) {
  console.log('\n── Downloading images ───────────────────────────────────────')
  const imageUpdates = []

  for (const p of spec.plants) {
    const slug = p.name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '')
    const page = p.wikipediaPage || p.name

    process.stdout.write(`  ${p.name}… `)

    let url
    try { url = await fetchWikipediaImageUrl(page) } catch { url = null }

    if (!url) {
      console.log('no image found on Wikipedia — skipping')
      continue
    }

    const rawExt = url.split('.').pop().split('?')[0].toLowerCase()
    const ext    = rawExt === 'png' ? 'png' : 'jpg'
    const fname  = `${slug}.${ext}`
    const dest   = path.join(IMAGES_DIR, fname)

    try {
      const imgRes = await httpsGet(url)
      if (imgRes.status !== 200) { console.log(`HTTP ${imgRes.status} — skipping`); continue }
      fs.writeFileSync(dest, imgRes.body)
      const kb = Math.round(imgRes.body.length / 1024)
      console.log(`${fname} (${kb} KB)`)
      imageUpdates.push({ name: p.name, path: `/images/plants/${fname}` })
    } catch (e) {
      console.log(`error: ${e.message}`)
    }
  }

  return imageUpdates
}

// ── New category check ────────────────────────────────────────────────────────

function checkNewCategories(spec) {
  const KNOWN_CATEGORIES = ['Fruiting', 'Leafy', 'Brassica', 'Root', 'Legume', 'Herb', 'Flower', 'Sea', 'Fruit']
  const used = [...new Set(spec.plants.map(p => p.category))]
  const novel = used.filter(c => !KNOWN_CATEGORIES.includes(c))
  if (novel.length) {
    console.log(`\n⚠️  New categories detected: ${novel.join(', ')}`)
    console.log(`   Remember to:`)
    console.log(`   1. Add to CATEGORY_ORDER in frontend/src/views/HomeView.vue`)
    console.log(`   2. Add to the 'categories' section in both en.js and nl.js`)
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const args      = process.argv.slice(2)
  const specFile  = args.find(a => !a.startsWith('--'))
  const withImages = args.includes('--images')

  if (!specFile) {
    console.error('Usage: node scripts/add-plants.js path/to/spec.json [--images]')
    console.error('       See scripts/plant-spec.example.json for the format.')
    process.exit(1)
  }

  const specPath = path.resolve(process.cwd(), specFile)
  if (!fs.existsSync(specPath)) {
    console.error(`Error: spec file not found: ${specPath}`)
    process.exit(1)
  }

  const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'))

  if (!spec.plants?.length) {
    console.error('Error: spec.plants is empty.')
    process.exit(1)
  }

  // Download images first so image_url UPDATEs can be included in the same migration
  let imageUpdates = []
  if (withImages) {
    imageUpdates = await downloadImages(spec)
    // Inject image paths back into spec so generateSQL can use them
    for (const upd of imageUpdates) {
      const plant = spec.plants.find(p => p.name === upd.name)
      if (plant) plant._imageUrl = upd.path
    }
  }

  const version = nextVersion()
  const { sql, desc } = generateSQL(spec, imageUpdates)
  const migrationName  = `V${version}__${desc}.sql`
  const migrationPath  = path.join(MIGRATIONS, migrationName)

  fs.writeFileSync(migrationPath, sql, 'utf8')
  console.log(`\n✅ Migration written: src/main/resources/db/migration/${migrationName}`)

  console.log(`\n──────────────────────────────────────────────────────`)
  console.log(`  i18n snippets — en.js`)
  console.log(`──────────────────────────────────────────────────────`)
  console.log(generateI18n(spec, 'en'))

  console.log(`──────────────────────────────────────────────────────`)
  console.log(`  i18n snippets — nl.js`)
  console.log(`──────────────────────────────────────────────────────`)
  console.log(generateI18n(spec, 'nl'))

  checkNewCategories(spec)

  console.log(`\n──────────────────────────────────────────────────────`)
  console.log(`  Next steps`)
  console.log(`──────────────────────────────────────────────────────`)
  console.log(`  1. Paste the i18n snippets above into en.js and nl.js`)
  console.log(`  2. Start the backend — Flyway will run the migration automatically`)
  console.log(`  3. Verify in the app that plants appear correctly`)
}

main()
