UPDATE vegetables SET image_url = '/images/vegetables/tomato.jpg' WHERE name = 'Tomato';
UPDATE vegetables SET image_url = '/images/vegetables/cucumber.jpg' WHERE name = 'Cucumber';
UPDATE vegetables SET image_url = '/images/vegetables/bell_pepper.jpg' WHERE name = 'Bell Pepper';
UPDATE vegetables SET image_url = '/images/vegetables/zucchini.jpg' WHERE name = 'Zucchini';
UPDATE vegetables SET image_url = '/images/vegetables/pumpkin.jpg' WHERE name = 'Pumpkin';
UPDATE vegetables SET image_url = '/images/vegetables/sweetcorn.jpg' WHERE name = 'Sweetcorn';
UPDATE vegetables SET image_url = '/images/vegetables/lettuce.jpg' WHERE name = 'Lettuce';
UPDATE vegetables SET image_url = '/images/vegetables/spinach.jpg' WHERE name = 'Spinach';
UPDATE vegetables SET image_url = '/images/vegetables/rocket.jpg' WHERE name = 'Rocket';
UPDATE vegetables SET image_url = '/images/vegetables/kale.jpg' WHERE name = 'Kale';
UPDATE vegetables SET image_url = '/images/vegetables/cabbage.jpg' WHERE name = 'Cabbage';
UPDATE vegetables SET image_url = '/images/vegetables/broccoli.jpg' WHERE name = 'Broccoli';
UPDATE vegetables SET image_url = '/images/vegetables/cauliflower.jpg' WHERE name = 'Cauliflower';
UPDATE vegetables SET image_url = '/images/vegetables/carrot.jpg' WHERE name = 'Carrot';
UPDATE vegetables SET image_url = '/images/vegetables/radish.jpg' WHERE name = 'Radish';
UPDATE vegetables SET image_url = '/images/vegetables/beetroot.png' WHERE name = 'Beetroot';
UPDATE vegetables SET image_url = '/images/vegetables/potato.jpg' WHERE name = 'Potato';
UPDATE vegetables SET image_url = '/images/vegetables/sweet_potato.jpg' WHERE name = 'Sweet Potato';
UPDATE vegetables SET image_url = '/images/vegetables/onion.jpg' WHERE name = 'Onion';
UPDATE vegetables SET image_url = '/images/vegetables/leek.jpg' WHERE name = 'Leek';
UPDATE vegetables SET image_url = '/images/vegetables/garlic.jpg' WHERE name = 'Garlic';
UPDATE vegetables SET image_url = '/images/vegetables/shallot.jpg' WHERE name = 'Shallot';
UPDATE vegetables SET image_url = '/images/vegetables/spring_onion.jpg' WHERE name = 'Spring Onion';
UPDATE vegetables SET image_url = '/images/vegetables/asparagus.jpg' WHERE name = 'Asparagus';
UPDATE vegetables SET image_url = '/images/vegetables/pea.jpg' WHERE name = 'Pea';
UPDATE vegetables SET image_url = '/images/vegetables/broad_bean.jpg' WHERE name = 'Broad Bean';
UPDATE vegetables SET image_url = '/images/vegetables/runner_bean.jpg' WHERE name = 'Runner Bean';
UPDATE vegetables SET image_url = '/images/vegetables/snap_pea.jpg' WHERE name = 'Snap Pea';
UPDATE vegetables SET image_url = '/images/vegetables/lentil.png' WHERE name = 'Lentil';
UPDATE vegetables SET image_url = '/images/vegetables/bean.jpg' WHERE name = 'Bean';
UPDATE vegetables SET image_url = '/images/vegetables/celery.jpg' WHERE name = 'Celery';
UPDATE vegetables SET image_url = '/images/vegetables/celeriac.jpg' WHERE name = 'Celeriac';
UPDATE vegetables SET image_url = '/images/vegetables/parsnip.jpg' WHERE name = 'Parsnip';
UPDATE vegetables SET image_url = '/images/vegetables/turnip.jpg' WHERE name = 'Turnip';
UPDATE vegetables SET image_url = '/images/vegetables/jerusalem_artichoke.jpg' WHERE name = 'Jerusalem Artichoke';
UPDATE vegetables SET image_url = '/images/vegetables/daikon.png' WHERE name = 'Daikon';
UPDATE vegetables SET image_url = '/images/vegetables/kohlrabi.jpg' WHERE name = 'Kohlrabi';
UPDATE vegetables SET image_url = '/images/vegetables/eggplant.JPG' WHERE name = 'Eggplant';
UPDATE vegetables SET image_url = '/images/vegetables/watermelon.jpg' WHERE name = 'Watermelon';
UPDATE vegetables SET image_url = '/images/vegetables/tomatillo.jpg' WHERE name = 'Tomatillo';
UPDATE vegetables SET image_url = '/images/vegetables/chili_pepper.jpg' WHERE name = 'Chili Pepper';
UPDATE vegetables SET image_url = '/images/vegetables/ginger.jpg' WHERE name = 'Ginger';
UPDATE vegetables SET image_url = '/images/vegetables/turmeric.jpg' WHERE name = 'Turmeric';
UPDATE vegetables SET image_url = '/images/vegetables/basil.jpg' WHERE name = 'Basil';
UPDATE vegetables SET image_url = '/images/vegetables/coriander.jpg' WHERE name = 'Coriander';
UPDATE vegetables SET image_url = '/images/vegetables/parsley.jpg' WHERE name = 'Parsley';
UPDATE vegetables SET image_url = '/images/vegetables/thyme.jpg' WHERE name = 'Thyme';
UPDATE vegetables SET image_url = '/images/vegetables/oregano.jpg' WHERE name = 'Oregano';
UPDATE vegetables SET image_url = '/images/vegetables/rosemary.JPG' WHERE name = 'Rosemary';
UPDATE vegetables SET image_url = '/images/vegetables/chive.jpg' WHERE name = 'Chive';
UPDATE vegetables SET image_url = '/images/vegetables/dill.jpg' WHERE name = 'Dill';
UPDATE vegetables SET image_url = '/images/vegetables/mint.jpg' WHERE name = 'Mint';
UPDATE vegetables SET image_url = '/images/vegetables/sage.jpg' WHERE name = 'Sage';
UPDATE vegetables SET image_url = '/images/vegetables/lemongrass.jpg' WHERE name = 'Lemongrass';
UPDATE vegetables SET image_url = '/images/vegetables/fennel.jpg' WHERE name = 'Fennel';
UPDATE vegetables SET image_url = '/images/vegetables/sorrel.jpg' WHERE name = 'Sorrel';
UPDATE vegetables SET image_url = '/images/vegetables/chicory.jpg' WHERE name = 'Chicory';
UPDATE vegetables SET image_url = '/images/vegetables/endive.jpg' WHERE name = 'Endive';
UPDATE vegetables SET image_url = '/images/vegetables/radicchio.jpg' WHERE name = 'Radicchio';
UPDATE vegetables SET image_url = '/images/vegetables/swiss_chard.jpg' WHERE name = 'Swiss Chard';
UPDATE vegetables SET image_url = '/images/vegetables/bok_choy.jpg' WHERE name = 'Bok Choy';
UPDATE vegetables SET image_url = '/images/vegetables/watercress.jpg' WHERE name = 'Watercress';
UPDATE vegetables SET image_url = '/images/vegetables/collard_greens.jpg' WHERE name = 'Collard Greens';
UPDATE vegetables SET image_url = '/images/vegetables/mustard_greens.jpg' WHERE name = 'Mustard Greens';
UPDATE vegetables SET image_url = '/images/vegetables/mizuna.jpg' WHERE name = 'Mizuna';
UPDATE vegetables SET image_url = '/images/vegetables/lamb_s_lettuce.jpg' WHERE name = 'Lamb''s Lettuce';
UPDATE vegetables SET image_url = '/images/vegetables/chervil.jpg' WHERE name = 'Chervil';
UPDATE vegetables SET image_url = '/images/vegetables/soybean.jpg' WHERE name = 'Soybean';
UPDATE vegetables SET image_url = '/images/vegetables/artichoke.jpg' WHERE name = 'Artichoke';
UPDATE vegetables SET image_url = '/images/vegetables/brussels_sprouts.jpg' WHERE name = 'Brussels Sprouts';
UPDATE vegetables SET image_url = '/images/vegetables/napa_cabbage.png' WHERE name = 'Napa Cabbage';
UPDATE vegetables SET image_url = '/images/vegetables/rapini.jpg' WHERE name = 'Rapini';
UPDATE vegetables SET image_url = '/images/vegetables/borage.jpg' WHERE name = 'Borage';
UPDATE vegetables SET image_url = '/images/vegetables/caraway.jpg' WHERE name = 'Caraway';
UPDATE vegetables SET image_url = '/images/vegetables/celtuce.jpg' WHERE name = 'Celtuce';
UPDATE vegetables SET image_url = '/images/vegetables/common_purslane.jpg' WHERE name = 'Common Purslane';
UPDATE vegetables SET image_url = '/images/vegetables/cress.jpg' WHERE name = 'Cress';
UPDATE vegetables SET image_url = '/images/vegetables/dandelion.jpg' WHERE name = 'Dandelion';
UPDATE vegetables SET image_url = '/images/vegetables/fiddlehead.png' WHERE name = 'Fiddlehead';
UPDATE vegetables SET image_url = '/images/vegetables/garland_chrysanthemum.jpg' WHERE name = 'Garland Chrysanthemum';
UPDATE vegetables SET image_url = '/images/vegetables/grape_leaves.jpg' WHERE name = 'Grape Leaves';
UPDATE vegetables SET image_url = '/images/vegetables/jute_mallow.jpg' WHERE name = 'Jute Mallow';
UPDATE vegetables SET image_url = '/images/vegetables/kai_lan.jpg' WHERE name = 'Kai-lan';
UPDATE vegetables SET image_url = '/images/vegetables/kalette.jpg' WHERE name = 'Kalette';
UPDATE vegetables SET image_url = '/images/vegetables/komatsuna.jpg' WHERE name = 'Komatsuna';
UPDATE vegetables SET image_url = '/images/vegetables/lamb_s_quarters.jpg' WHERE name = 'Lamb''s Quarters';
UPDATE vegetables SET image_url = '/images/vegetables/land_cress.jpg' WHERE name = 'Land Cress';
UPDATE vegetables SET image_url = '/images/vegetables/malabar_spinach.jpg' WHERE name = 'Malabar Spinach';
UPDATE vegetables SET image_url = '/images/vegetables/mallow.jpg' WHERE name = 'Mallow';
UPDATE vegetables SET image_url = '/images/vegetables/miners_lettuce.JPG' WHERE name = 'Miner''s Lettuce';
UPDATE vegetables SET image_url = '/images/vegetables/moringa.jpg' WHERE name = 'Moringa';
UPDATE vegetables SET image_url = '/images/vegetables/new_zealand_spinach.jpg' WHERE name = 'New Zealand Spinach';
UPDATE vegetables SET image_url = '/images/vegetables/orache.png' WHERE name = 'Orache';
UPDATE vegetables SET image_url = '/images/vegetables/samphire.jpg' WHERE name = 'Samphire';
UPDATE vegetables SET image_url = '/images/vegetables/sea_beet.jpg' WHERE name = 'Sea Beet';
UPDATE vegetables SET image_url = '/images/vegetables/sea_kale.jpg' WHERE name = 'Sea Kale';
UPDATE vegetables SET image_url = '/images/vegetables/tatsoi.jpg' WHERE name = 'Tatsoi';
UPDATE vegetables SET image_url = '/images/vegetables/water_spinach.jpg' WHERE name = 'Water Spinach';
UPDATE vegetables SET image_url = '/images/vegetables/wheatgrass.jpg' WHERE name = 'Wheatgrass';
UPDATE vegetables SET image_url = '/images/vegetables/yao_choy.jpg' WHERE name = 'Yao Choy';
UPDATE vegetables SET image_url = '/images/vegetables/chickweed.jpg' WHERE name = 'Chickweed';
UPDATE vegetables SET image_url = '/images/vegetables/bitter_melon.png' WHERE name = 'Bitter Melon';
UPDATE vegetables SET image_url = '/images/vegetables/butternut_squash.jpg' WHERE name = 'Butternut Squash';
UPDATE vegetables SET image_url = '/images/vegetables/calabash.jpg' WHERE name = 'Calabash';
UPDATE vegetables SET image_url = '/images/vegetables/chayote.jpg' WHERE name = 'Chayote';
UPDATE vegetables SET image_url = '/images/vegetables/cucamelon.jpg' WHERE name = 'Cucamelon';
UPDATE vegetables SET image_url = '/images/vegetables/kabocha.jpg' WHERE name = 'Kabocha';
UPDATE vegetables SET image_url = '/images/vegetables/luffa.jpg' WHERE name = 'Luffa';
UPDATE vegetables SET image_url = '/images/vegetables/spaghetti_squash.jpg' WHERE name = 'Spaghetti Squash';
UPDATE vegetables SET image_url = '/images/vegetables/winter_melon.jpg' WHERE name = 'Winter Melon';
UPDATE vegetables SET image_url = '/images/vegetables/jalapeno.jpg' WHERE name = 'Jalapeño';
UPDATE vegetables SET image_url = '/images/vegetables/habanero.jpg' WHERE name = 'Habanero';
UPDATE vegetables SET image_url = '/images/vegetables/cayenne_pepper.jpg' WHERE name = 'Cayenne Pepper';
UPDATE vegetables SET image_url = '/images/vegetables/banana_flower.jpg' WHERE name = 'Banana Flower';
UPDATE vegetables SET image_url = '/images/vegetables/caper.jpg' WHERE name = 'Caper';
UPDATE vegetables SET image_url = '/images/vegetables/daylily.jpg' WHERE name = 'Daylily';
UPDATE vegetables SET image_url = '/images/vegetables/loroco.jpg' WHERE name = 'Loroco';
UPDATE vegetables SET image_url = '/images/vegetables/asparagus_bean.jpg' WHERE name = 'Asparagus Bean';
UPDATE vegetables SET image_url = '/images/vegetables/adzuki_bean.jpg' WHERE name = 'Adzuki Bean';
UPDATE vegetables SET image_url = '/images/vegetables/black_eyed_pea.jpg' WHERE name = 'Black-eyed Pea';
UPDATE vegetables SET image_url = '/images/vegetables/chickpea.jpg' WHERE name = 'Chickpea';
UPDATE vegetables SET image_url = '/images/vegetables/lima_bean.jpg' WHERE name = 'Lima Bean';
UPDATE vegetables SET image_url = '/images/vegetables/mung_bean.jpg' WHERE name = 'Mung Bean';
UPDATE vegetables SET image_url = '/images/vegetables/okra.jpg' WHERE name = 'Okra';
UPDATE vegetables SET image_url = '/images/vegetables/snow_pea.jpg' WHERE name = 'Snow Pea';
UPDATE vegetables SET image_url = '/images/vegetables/winged_bean.png' WHERE name = 'Winged Bean';
UPDATE vegetables SET image_url = '/images/vegetables/bamboo_shoot.jpg' WHERE name = 'Bamboo Shoot';
UPDATE vegetables SET image_url = '/images/vegetables/burdock.jpg' WHERE name = 'Burdock';
UPDATE vegetables SET image_url = '/images/vegetables/cassava.jpg' WHERE name = 'Cassava';
UPDATE vegetables SET image_url = '/images/vegetables/galangal.jpg' WHERE name = 'Galangal';
UPDATE vegetables SET image_url = '/images/vegetables/hamburg_parsley.jpg' WHERE name = 'Hamburg Parsley';
UPDATE vegetables SET image_url = '/images/vegetables/horseradish.jpg' WHERE name = 'Horseradish';
UPDATE vegetables SET image_url = '/images/vegetables/jicama.png' WHERE name = 'Jicama';
UPDATE vegetables SET image_url = '/images/vegetables/rutabaga.jpg' WHERE name = 'Rutabaga';
UPDATE vegetables SET image_url = '/images/vegetables/salsify.jpg' WHERE name = 'Salsify';
UPDATE vegetables SET image_url = '/images/vegetables/scorzonera.jpg' WHERE name = 'Scorzonera';
UPDATE vegetables SET image_url = '/images/vegetables/taro.jpg' WHERE name = 'Taro';
UPDATE vegetables SET image_url = '/images/vegetables/tigernut.jpg' WHERE name = 'Tigernut';
UPDATE vegetables SET image_url = '/images/vegetables/wasabi.jpg' WHERE name = 'Wasabi';
UPDATE vegetables SET image_url = '/images/vegetables/water_chestnut.jpg' WHERE name = 'Water Chestnut';
UPDATE vegetables SET image_url = '/images/vegetables/yam.jpg' WHERE name = 'Yam';
UPDATE vegetables SET image_url = '/images/vegetables/cardoon.jpg' WHERE name = 'Cardoon';
UPDATE vegetables SET image_url = '/images/vegetables/elephant_garlic.jpg' WHERE name = 'Elephant Garlic';
UPDATE vegetables SET image_url = '/images/vegetables/lotus_root.jpg' WHERE name = 'Lotus Root';
UPDATE vegetables SET image_url = '/images/vegetables/nopal.jpg' WHERE name = 'Nopal';
UPDATE vegetables SET image_url = '/images/vegetables/welsh_onion.jpg' WHERE name = 'Welsh Onion';
UPDATE vegetables SET image_url = '/images/vegetables/wild_leek.jpeg' WHERE name = 'Wild Leek';
UPDATE vegetables SET image_url = '/images/vegetables/aonori.jpg' WHERE name = 'Aonori';
UPDATE vegetables SET image_url = '/images/vegetables/arame.png' WHERE name = 'Arame';
UPDATE vegetables SET image_url = '/images/vegetables/dulse.jpg' WHERE name = 'Dulse';
UPDATE vegetables SET image_url = '/images/vegetables/hijiki.jpg' WHERE name = 'Hijiki';
UPDATE vegetables SET image_url = '/images/vegetables/kombu.jpg' WHERE name = 'Kombu';
UPDATE vegetables SET image_url = '/images/vegetables/nori.jpg' WHERE name = 'Nori';
UPDATE vegetables SET image_url = '/images/vegetables/sea_lettuce.jpg' WHERE name = 'Sea Lettuce';
UPDATE vegetables SET image_url = '/images/vegetables/sea_grape.jpg' WHERE name = 'Sea Grape';
UPDATE vegetables SET image_url = '/images/vegetables/wakame.jpg' WHERE name = 'Wakame';
UPDATE vegetables SET image_url = '/images/vegetables/squash.jpg' WHERE name = 'Squash';
