UPDATE pts_plants SET latin_name = 'Solanum lycopersicum'               WHERE name = 'Tomato';
UPDATE pts_plants SET latin_name = 'Cucumis sativus'                    WHERE name = 'Cucumber';
UPDATE pts_plants SET latin_name = 'Capsicum annuum'                    WHERE name = 'Bell Pepper';
UPDATE pts_plants SET latin_name = 'Cucurbita pepo'                     WHERE name = 'Zucchini';
UPDATE pts_plants SET latin_name = 'Cucurbita maxima'                   WHERE name = 'Pumpkin';
UPDATE pts_plants SET latin_name = 'Zea mays'                           WHERE name = 'Sweetcorn';
UPDATE pts_plants SET latin_name = 'Lactuca sativa'                     WHERE name = 'Lettuce';
UPDATE pts_plants SET latin_name = 'Spinacia oleracea'                  WHERE name = 'Spinach';
UPDATE pts_plants SET latin_name = 'Eruca vesicaria'                    WHERE name = 'Rocket';
UPDATE pts_plants SET latin_name = 'Brassica oleracea var. sabellica'   WHERE name = 'Kale';
UPDATE pts_plants SET latin_name = 'Brassica oleracea var. capitata'    WHERE name = 'Cabbage';
UPDATE pts_plants SET latin_name = 'Brassica oleracea var. italica'     WHERE name = 'Broccoli';
UPDATE pts_plants SET latin_name = 'Brassica oleracea var. botrytis'    WHERE name = 'Cauliflower';
UPDATE pts_plants SET latin_name = 'Daucus carota'                      WHERE name = 'Carrot';
UPDATE pts_plants SET latin_name = 'Raphanus sativus'                   WHERE name = 'Radish';
UPDATE pts_plants SET latin_name = 'Beta vulgaris'                      WHERE name = 'Beetroot';
UPDATE pts_plants SET latin_name = 'Allium cepa'                        WHERE name = 'Onion';
UPDATE pts_plants SET latin_name = 'Allium ampeloprasum'                WHERE name = 'Leek';
UPDATE pts_plants SET latin_name = 'Pisum sativum'                      WHERE name = 'Pea';
UPDATE pts_plants SET latin_name = 'Phaseolus vulgaris'                 WHERE name = 'Bean';
UPDATE pts_plants SET latin_name = 'Petroselinum crispum'               WHERE name = 'Parsley';
UPDATE pts_plants SET latin_name = 'Ocimum basilicum'                   WHERE name = 'Basil';
UPDATE pts_plants SET latin_name = 'Anethum graveolens'                 WHERE name = 'Dill';
UPDATE pts_plants SET latin_name = 'Foeniculum vulgare'                 WHERE name = 'Fennel';

UPDATE pts_plants SET latin_name = 'Brassica rapa subsp. chinensis'     WHERE name = 'Bok Choy';
UPDATE pts_plants SET latin_name = 'Beta vulgaris subsp. vulgaris'      WHERE name = 'Swiss Chard';
UPDATE pts_plants SET latin_name = 'Nasturtium officinale'              WHERE name = 'Watercress';
UPDATE pts_plants SET latin_name = 'Cichorium endivia'                  WHERE name = 'Endive';
UPDATE pts_plants SET latin_name = 'Cichorium intybus'                  WHERE name = 'Radicchio';
UPDATE pts_plants SET latin_name = 'Cichorium intybus'                  WHERE name = 'Chicory';
UPDATE pts_plants SET latin_name = 'Valerianella locusta'               WHERE name = 'Lamb''s Lettuce';
UPDATE pts_plants SET latin_name = 'Rumex acetosa'                      WHERE name = 'Sorrel';
UPDATE pts_plants SET latin_name = 'Brassica rapa subsp. nipposinica'   WHERE name = 'Mizuna';
UPDATE pts_plants SET latin_name = 'Brassica oleracea var. viridis'     WHERE name = 'Collard Greens';
UPDATE pts_plants SET latin_name = 'Brassica juncea'                    WHERE name = 'Mustard Greens';
UPDATE pts_plants SET latin_name = 'Cynara cardunculus var. scolymus'   WHERE name = 'Artichoke';
UPDATE pts_plants SET latin_name = 'Brassica oleracea var. gemmifera'   WHERE name = 'Brussels Sprouts';
UPDATE pts_plants SET latin_name = 'Brassica oleracea var. gongylodes'  WHERE name = 'Kohlrabi';
UPDATE pts_plants SET latin_name = 'Brassica rapa subsp. rapa'          WHERE name = 'Turnip';
UPDATE pts_plants SET latin_name = 'Brassica rapa subsp. pekinensis'    WHERE name = 'Napa Cabbage';
UPDATE pts_plants SET latin_name = 'Brassica rapa subsp. sylvestris'    WHERE name = 'Rapini';
UPDATE pts_plants SET latin_name = 'Solanum melongena'                  WHERE name = 'Eggplant';
UPDATE pts_plants SET latin_name = 'Capsicum annuum'                    WHERE name = 'Chili Pepper';
UPDATE pts_plants SET latin_name = 'Cucurbita pepo'                     WHERE name = 'Squash';
UPDATE pts_plants SET latin_name = 'Solanum tuberosum'                  WHERE name = 'Potato';
UPDATE pts_plants SET latin_name = 'Ipomoea batatas'                    WHERE name = 'Sweet Potato';
UPDATE pts_plants SET latin_name = 'Pastinaca sativa'                   WHERE name = 'Parsnip';
UPDATE pts_plants SET latin_name = 'Helianthus tuberosus'               WHERE name = 'Jerusalem Artichoke';
UPDATE pts_plants SET latin_name = 'Apium graveolens var. rapaceum'     WHERE name = 'Celeriac';
UPDATE pts_plants SET latin_name = 'Raphanus sativus var. longipinnatus' WHERE name = 'Daikon';
UPDATE pts_plants SET latin_name = 'Allium sativum'                     WHERE name = 'Garlic';
UPDATE pts_plants SET latin_name = 'Allium ascalonicum'                 WHERE name = 'Shallot';
UPDATE pts_plants SET latin_name = 'Allium fistulosum'                  WHERE name = 'Spring Onion';
UPDATE pts_plants SET latin_name = 'Apium graveolens'                   WHERE name = 'Celery';
UPDATE pts_plants SET latin_name = 'Asparagus officinalis'              WHERE name = 'Asparagus';
UPDATE pts_plants SET latin_name = 'Vicia faba'                         WHERE name = 'Broad Bean';
UPDATE pts_plants SET latin_name = 'Phaseolus coccineus'                WHERE name = 'Runner Bean';
UPDATE pts_plants SET latin_name = 'Pisum sativum var. macrocarpon'     WHERE name = 'Snap Pea';
UPDATE pts_plants SET latin_name = 'Lens culinaris'                     WHERE name = 'Lentil';
UPDATE pts_plants SET latin_name = 'Glycine max'                        WHERE name = 'Soybean';
UPDATE pts_plants SET latin_name = 'Allium schoenoprasum'               WHERE name = 'Chive';
UPDATE pts_plants SET latin_name = 'Coriandrum sativum'                 WHERE name = 'Coriander';
UPDATE pts_plants SET latin_name = 'Mentha spicata'                     WHERE name = 'Mint';
UPDATE pts_plants SET latin_name = 'Thymus vulgaris'                    WHERE name = 'Thyme';
UPDATE pts_plants SET latin_name = 'Salvia rosmarinus'                  WHERE name = 'Rosemary';
UPDATE pts_plants SET latin_name = 'Origanum vulgare'                   WHERE name = 'Oregano';
UPDATE pts_plants SET latin_name = 'Salvia officinalis'                 WHERE name = 'Sage';
UPDATE pts_plants SET latin_name = 'Anthriscus cerefolium'              WHERE name = 'Chervil';
UPDATE pts_plants SET latin_name = 'Cymbopogon citratus'                WHERE name = 'Lemongrass';

UPDATE pts_plants SET latin_name = 'Stellaria media'                    WHERE name = 'Chickweed';

UPDATE pts_plants SET latin_name = 'Borago officinalis'                 WHERE name = 'Borage';
UPDATE pts_plants SET latin_name = 'Carum carvi'                        WHERE name = 'Caraway';
UPDATE pts_plants SET latin_name = 'Lactuca sativa var. augustana'      WHERE name = 'Celtuce';
UPDATE pts_plants SET latin_name = 'Portulaca oleracea'                 WHERE name = 'Common Purslane';
UPDATE pts_plants SET latin_name = 'Lepidium sativum'                   WHERE name = 'Cress';
UPDATE pts_plants SET latin_name = 'Taraxacum officinale'               WHERE name = 'Dandelion';
UPDATE pts_plants SET latin_name = 'Matteuccia struthiopteris'          WHERE name = 'Fiddlehead';
UPDATE pts_plants SET latin_name = 'Glebionis coronaria'                WHERE name = 'Garland Chrysanthemum';
UPDATE pts_plants SET latin_name = 'Vitis vinifera'                     WHERE name = 'Grape Leaves';
UPDATE pts_plants SET latin_name = 'Corchorus olitorius'                WHERE name = 'Jute Mallow';
UPDATE pts_plants SET latin_name = 'Brassica oleracea var. alboglabra'  WHERE name = 'Kai-lan';
UPDATE pts_plants SET latin_name = 'Brassica oleracea (hybrid)'         WHERE name = 'Kalette';
UPDATE pts_plants SET latin_name = 'Brassica rapa var. perviridis'      WHERE name = 'Komatsuna';
UPDATE pts_plants SET latin_name = 'Chenopodium album'                  WHERE name = 'Lamb''s Quarters';
UPDATE pts_plants SET latin_name = 'Barbarea verna'                     WHERE name = 'Land Cress';
UPDATE pts_plants SET latin_name = 'Basella alba'                       WHERE name = 'Malabar Spinach';
UPDATE pts_plants SET latin_name = 'Malva sylvestris'                   WHERE name = 'Mallow';
UPDATE pts_plants SET latin_name = 'Claytonia perfoliata'               WHERE name = 'Miner''s Lettuce';
UPDATE pts_plants SET latin_name = 'Moringa oleifera'                   WHERE name = 'Moringa';
UPDATE pts_plants SET latin_name = 'Tetragonia tetragonioides'          WHERE name = 'New Zealand Spinach';
UPDATE pts_plants SET latin_name = 'Atriplex hortensis'                 WHERE name = 'Orache';
UPDATE pts_plants SET latin_name = 'Crithmum maritimum'                 WHERE name = 'Samphire';
UPDATE pts_plants SET latin_name = 'Beta vulgaris subsp. maritima'      WHERE name = 'Sea Beet';
UPDATE pts_plants SET latin_name = 'Crambe maritima'                    WHERE name = 'Sea Kale';
UPDATE pts_plants SET latin_name = 'Brassica rapa subsp. narinosa'      WHERE name = 'Tatsoi';
UPDATE pts_plants SET latin_name = 'Ipomoea aquatica'                   WHERE name = 'Water Spinach';
UPDATE pts_plants SET latin_name = 'Triticum aestivum'                  WHERE name = 'Wheatgrass';
UPDATE pts_plants SET latin_name = 'Brassica rapa subsp. parachinensis' WHERE name = 'Yao Choy';
UPDATE pts_plants SET latin_name = 'Momordica charantia'                WHERE name = 'Bitter Melon';
UPDATE pts_plants SET latin_name = 'Cucurbita moschata'                 WHERE name = 'Butternut Squash';
UPDATE pts_plants SET latin_name = 'Lagenaria siceraria'                WHERE name = 'Calabash';
UPDATE pts_plants SET latin_name = 'Sechium edule'                      WHERE name = 'Chayote';
UPDATE pts_plants SET latin_name = 'Melothria scabra'                   WHERE name = 'Cucamelon';
UPDATE pts_plants SET latin_name = 'Cucurbita maxima'                   WHERE name = 'Kabocha';
UPDATE pts_plants SET latin_name = 'Luffa aegyptiaca'                   WHERE name = 'Luffa';
UPDATE pts_plants SET latin_name = 'Cucurbita pepo'                     WHERE name = 'Spaghetti Squash';
UPDATE pts_plants SET latin_name = 'Physalis philadelphica'             WHERE name = 'Tomatillo';
UPDATE pts_plants SET latin_name = 'Citrullus lanatus'                  WHERE name = 'Watermelon';
UPDATE pts_plants SET latin_name = 'Benincasa hispida'                  WHERE name = 'Winter Melon';
UPDATE pts_plants SET latin_name = 'Capsicum annuum'                    WHERE name = 'Jalapeño';
UPDATE pts_plants SET latin_name = 'Capsicum chinense'                  WHERE name = 'Habanero';
UPDATE pts_plants SET latin_name = 'Capsicum annuum var. longum'        WHERE name = 'Cayenne Pepper';
UPDATE pts_plants SET latin_name = 'Musa acuminata'                     WHERE name = 'Banana Flower';
UPDATE pts_plants SET latin_name = 'Capparis spinosa'                   WHERE name = 'Caper';
UPDATE pts_plants SET latin_name = 'Hemerocallis fulva'                 WHERE name = 'Daylily';
UPDATE pts_plants SET latin_name = 'Fernaldia pandurata'                WHERE name = 'Loroco';
UPDATE pts_plants SET latin_name = 'Vigna unguiculata subsp. sesquipedalis' WHERE name = 'Asparagus Bean';
UPDATE pts_plants SET latin_name = 'Vigna angularis'                    WHERE name = 'Adzuki Bean';
UPDATE pts_plants SET latin_name = 'Vigna unguiculata'                  WHERE name = 'Black-eyed Pea';
UPDATE pts_plants SET latin_name = 'Cicer arietinum'                    WHERE name = 'Chickpea';
UPDATE pts_plants SET latin_name = 'Phaseolus lunatus'                  WHERE name = 'Lima Bean';
UPDATE pts_plants SET latin_name = 'Vigna radiata'                      WHERE name = 'Mung Bean';
UPDATE pts_plants SET latin_name = 'Abelmoschus esculentus'             WHERE name = 'Okra';
UPDATE pts_plants SET latin_name = 'Pisum sativum var. saccharatum'     WHERE name = 'Snow Pea';
UPDATE pts_plants SET latin_name = 'Psophocarpus tetragonolobus'        WHERE name = 'Winged Bean';
UPDATE pts_plants SET latin_name = 'Phyllostachys edulis'               WHERE name = 'Bamboo Shoot';
UPDATE pts_plants SET latin_name = 'Arctium lappa'                      WHERE name = 'Burdock';
UPDATE pts_plants SET latin_name = 'Manihot esculenta'                  WHERE name = 'Cassava';
UPDATE pts_plants SET latin_name = 'Alpinia galanga'                    WHERE name = 'Galangal';
UPDATE pts_plants SET latin_name = 'Zingiber officinale'                WHERE name = 'Ginger';
UPDATE pts_plants SET latin_name = 'Petroselinum crispum var. tuberosum' WHERE name = 'Hamburg Parsley';
UPDATE pts_plants SET latin_name = 'Armoracia rusticana'                WHERE name = 'Horseradish';
UPDATE pts_plants SET latin_name = 'Pachyrhizus erosus'                 WHERE name = 'Jicama';
UPDATE pts_plants SET latin_name = 'Brassica napus var. napobrassica'   WHERE name = 'Rutabaga';
UPDATE pts_plants SET latin_name = 'Tragopogon porrifolius'             WHERE name = 'Salsify';
UPDATE pts_plants SET latin_name = 'Scorzonera hispanica'               WHERE name = 'Scorzonera';
UPDATE pts_plants SET latin_name = 'Colocasia esculenta'                WHERE name = 'Taro';
UPDATE pts_plants SET latin_name = 'Cyperus esculentus'                 WHERE name = 'Tigernut';
UPDATE pts_plants SET latin_name = 'Curcuma longa'                      WHERE name = 'Turmeric';
UPDATE pts_plants SET latin_name = 'Eutrema japonicum'                  WHERE name = 'Wasabi';
UPDATE pts_plants SET latin_name = 'Eleocharis dulcis'                  WHERE name = 'Water Chestnut';
UPDATE pts_plants SET latin_name = 'Dioscorea alata'                    WHERE name = 'Yam';
UPDATE pts_plants SET latin_name = 'Cynara cardunculus'                 WHERE name = 'Cardoon';
UPDATE pts_plants SET latin_name = 'Allium ampeloprasum var. ampeloprasum' WHERE name = 'Elephant Garlic';
UPDATE pts_plants SET latin_name = 'Nelumbo nucifera'                   WHERE name = 'Lotus Root';
UPDATE pts_plants SET latin_name = 'Opuntia ficus-indica'               WHERE name = 'Nopal';
UPDATE pts_plants SET latin_name = 'Allium fistulosum'                  WHERE name = 'Welsh Onion';
UPDATE pts_plants SET latin_name = 'Allium tricoccum'                   WHERE name = 'Wild Leek';
UPDATE pts_plants SET latin_name = 'Monostroma nitidum'                 WHERE name = 'Aonori';
UPDATE pts_plants SET latin_name = 'Eisenia bicyclis'                   WHERE name = 'Arame';
UPDATE pts_plants SET latin_name = 'Palmaria palmata'                   WHERE name = 'Dulse';
UPDATE pts_plants SET latin_name = 'Sargassum fusiforme'                WHERE name = 'Hijiki';
UPDATE pts_plants SET latin_name = 'Saccharina japonica'                WHERE name = 'Kombu';
UPDATE pts_plants SET latin_name = 'Pyropia tenera'                     WHERE name = 'Nori';
UPDATE pts_plants SET latin_name = 'Ulva lactuca'                       WHERE name = 'Sea Lettuce';
UPDATE pts_plants SET latin_name = 'Caulerpa lentillifera'              WHERE name = 'Sea Grape';
UPDATE pts_plants SET latin_name = 'Undaria pinnatifida'                WHERE name = 'Wakame';

UPDATE pts_plants SET latin_name = 'Tropaeolum majus'                   WHERE name = 'Nasturtium';
UPDATE pts_plants SET latin_name = 'Calendula officinalis'              WHERE name = 'Calendula';
UPDATE pts_plants SET latin_name = 'Lavandula angustifolia'             WHERE name = 'Lavender';
UPDATE pts_plants SET latin_name = 'Viola tricolor'                     WHERE name = 'Viola';
UPDATE pts_plants SET latin_name = 'Helianthus annuus'                  WHERE name = 'Sunflower';
UPDATE pts_plants SET latin_name = 'Centaurea cyanus'                   WHERE name = 'Cornflower';
UPDATE pts_plants SET latin_name = 'Matricaria chamomilla'              WHERE name = 'Chamomile';
UPDATE pts_plants SET latin_name = 'Sambucus nigra'                     WHERE name = 'Elderflower';
UPDATE pts_plants SET latin_name = 'Rosa canina'                        WHERE name = 'Rose';

UPDATE pts_plants SET latin_name = 'Artemisia dracunculus'              WHERE name = 'Tarragon';
UPDATE pts_plants SET latin_name = 'Levisticum officinale'              WHERE name = 'Lovage';
UPDATE pts_plants SET latin_name = 'Brassica oleracea var. palmifolia'  WHERE name = 'Lacinato Kale';
